### ISSUE TITLE
base image can't be store under specified path

### ISSUE THREAD

**Issue by gtycherry** [mjhea0/cypress-visual-regression#9] opened 2019-03-08 07:47 UTC
When integrated cypress-visual-regression with cypress, and run command:
cypress run type=base --config screenshotsFolder=cypress/results/snapshots/base
the base image can't be placed under path 'cypress/results/snapshots/base'.
Can anybody give some suggestion?

**Comment by damiano-carradori** [comment] 2019-05-28 13:36
I've just try to run it, but I didn't get any error and the images are inside the `cypress/results/snapshots/base` folder.

Can you attach the error that you receive?

**Comment by mjhea0** [comment] 2019-07-02 02:34
closing in favor of https://github.com/mjhea0/cypress-visual-regression/issues/13

**Closed by mjhea0** 2019-07-02 02:34 UTC

**Comment by jbutko** [comment] 2019-11-11 10:45
I had a very similar issue that base snapshots were not created in specified folder which I have passed via `--config screenshotsFolder=...` flag in command line. I figured out that I did not passed `config` flag correctly. At first I did following:
```
.\node_modules\.bin\cypress run --env type=base --config screenshotsFolder=cypress/snapshots/base --config testFiles=\"**/*regression-tests.js\"
```
See I duplicated `--config` option flag because I needed to specify file where regression tests were placed. And that's the issue. Based on [cypress command line documentation](https://docs.cypress.io/guides/references/configuration.html#Command-Line) if you are passing multiple options they need to be separated with comma. So the correct command should be:
```
.\node_modules\.bin\cypress run --env type=base --config screenshotsFolder=cypress/snapshots/base,testFiles=\"**/*regression-tests.js\"
```
After that fix all worked like a charm. Maybe this helps somebody else facing similar issue.

**Comment by mjhea0** [comment] 2019-11-11 13:53
@jbutko thanks for the note. I think it would be helpful to have that on the readme. Would you be up for updating it and submitting a PR?

**Comment by jbutko** [comment] 2019-11-11 15:28
@mjhea0 will try to find some time and do a PR.
