### ISSUE TITLE
Configured `actual` screenshot directory

### ISSUE THREAD

**Issue by MrRahulR** [mjhea0/cypress-visual-regression#118] opened 2022-03-09 18:51 UTC
### Problem

- While executing the Cypress tests, I'm running it with different viewports. I need to create separate folders for each running viewport.

- For the `base` and `diff` it already has configured by `SNAPSHOT_BASE_DIRECTORY` and `SNAPSHOT_DIFF_DIRECTORY` configuration.

 - Unfortunately for the `actual` the plugin has a defined default screenshot folder and can't be overwritten, so tests keep failing.

@mjhea0  - Would be great if `actual` can be also overridden and can have a configuration for the `actual` screenshots folder. 

Here is the example repository -
https://github.com/MrRahulR/swaglabs_cypress

**Comment by Zaista** [comment] 2022-04-20 18:52
I'm having trouble understanding your problem:
It sounds like all you really need is to configure the `screenshotFolder` property, which exists in vanilla cypress, which also serves as a destination for `actual` images in this plugin.
But then I saw that you already specified this property in your example repo in the `package.json` scripts and set it to `cypress/integration/actual` path.
Did you just misused the `sreecshotFolder` property, since I can't think of a reason why would it be different for base and actual scrips, or am I missing something here?

**Comment by MrRahulR** [comment] 2022-04-22 17:49
Okay let me try to rephrase it, 
I am running tests on multiple viewports and I have created a folder for each viewport in the `base` folder.

1. Executed the base commnad - 
`cypress open --env type=base --config screenshotsFolder=cypress/snapshots/base`

Now the `snapshots/base` will show the below folder structure. 

<img width="311" alt="Screenshot 2022-04-22 at 11 15 29 PM" src="https://user-images.githubusercontent.com/5868850/164767537-4c375f3d-ae9c-4cad-bd21-e85d1fda853b.png">

2. Now I'll run the actual command - 
`cypress open --env type=actual`

The tests fail as they can't find the proper path for the base screenshots, and shows the below error on cypress execution

<img width="457" alt="Screenshot 2022-04-22 at 11 13 53 PM" src="https://user-images.githubusercontent.com/5868850/164767727-f4aece82-0dcb-4a26-9a22-f9558ddf1322.png">

----
Is there any way I can make the same folder structure as the `base` for the `actual` folder?

**Comment by Zaista** [comment] 2022-04-28 15:01
Ok, I think the problem is that `cy.compareSnapshot()` command was designed to accept only a `name` of the image, and not a `path` of the image. Quick glance at the code shows that there's no proper parsing in place, and weirdly enough, `base` run creates proper folder structure as you would expect, but `actual` run fails as seen in your screen shot, because it recognizes a size folder as part of the image name. There is a workaround, but it's not ideal, and the resulting folder structure is a bit different than in your example, you can change `base` directory depending on the size on-the-fly, like this:

`
viewPorts.forEach((size) => {
        describe(`Verify screen: ${size}`, {env: {SNAPSHOT_BASE_DIRECTORY: `cypress/snapshots/base/${size}`}}, () => {

            it('Login Screen', () => {
                // test
                cy.compareSnapshot('Login Screen');
            });

            it('Dashboard Screen', () => {
                // test
                cy.compareSnapshot('Dashboard Screen');
            });
        });
    });
`

**Comment by Zaista** [comment] 2022-05-12 12:48
Closing the issue, if there's further needs to provide folder destinations next to the image name, please open a dedicated feature request.

**Closed by Zaista** 2022-05-12 12:48 UTC
