### ISSUE TITLE
Intermittent Error: [object Object] on compareSnapshot command

### ISSUE THREAD

**Issue by vineetbrikl** [mjhea0/cypress-visual-regression#84] opened 2021-06-24 14:24 UTC
![image](https://user-images.githubusercontent.com/78526621/123961937-18149780-d9db-11eb-8138-a276e85178b3.png)
All test in this screenshot are using Cypress visual regression to compare snapshot. Some of them pass and some fail because of the object Object error. 

Does someone know how to fix this? I don't know what more details are relevant to be share. But please let me know if anything else is required.

**Comment by adrienlucas** [comment] 2021-07-08 09:18
Same here, it thrown from https://github.com/mjhea0/cypress-visual-regression/blob/19cfe6ff583671c5b873a3aa91ae289a9ba91b73/src/command.js#L55  and the `results.error` is an empty object...

**Comment by azz0r** [comment] 2021-07-08 09:20
Also having the same issue, seems random though

**Comment by vineetbrikl** [comment] 2021-07-08 10:21
[object Object] is too vague of an error. I was able to reproduce the error locally by deleting the base image and running in actual mode. But this doesn't seem to be the case in CI, since base files are all stored in git and the CI process seems to be having appropriate access rights since other images in the same folders pass successfully. 

I know this is an obvious and stupid way to reproduce the error but just sharing.

**Comment by tdikarim** [comment] 2021-07-08 17:25
Hey,
I don't know if my issue is the same for you. I solved by fixing a separate folder for DIFF
like here : 
describe('xxxxxxxxxx', 
    {
      env: {
        SNAPSHOT_BASE_DIRECTORY: 'cypress/snapshots/base',
        SNAPSHOT_DIFF_DIRECTORY: 'cypress/snapshots/diff',
        failSilently: false  
      }
    },

**Comment by Krismix1** [comment] 2021-07-08 18:37
I am running into a similar situation in this is what I have discovered:
In plugin.js, there is a try-catch block, which catches exceptions and generated an "error" object.
https://github.com/mjhea0/cypress-visual-regression/blob/19cfe6ff583671c5b873a3aa91ae289a9ba91b73/src/plugin.js#L103
This return value is then checked in command.js.
https://github.com/mjhea0/cypress-visual-regression/blob/19cfe6ff583671c5b873a3aa91ae289a9ba91b73/src/command.js#L55 

In my case, if I manually modify the plugin.js in node_modules, and remove the try-catch, then the error is caught by Cypress, and I see the actual error message. Similarly, replacing the returned object with `{ error: error.message }` also works in my case.
(My particular error is caused by https://github.com/cypress-io/cypress/issues/15077, so the `error.message` works, but might not be the case for everyone). 

The question now becomes, is there any real advantage of having the try-catch block instead of letting the error bubble up?

Versions:
Cypress 7.6.0
cypress-visual-regression: 1.5.7

**Comment by PeterDekkers** [comment] 2021-07-13 01:06
To me it looks like some part of the code is ignoring the `screenshotsFolder` setting in `cypress.json`. When I let the error bubble up as per @Krismix1's suggestion then I get an error for a path that doesn't match my setting in `cypress.json`.

**Comment by PeterDekkers** [comment] 2021-07-13 01:09
Ah right, of course, so that would be due to this bug in Cypress I assume: https://github.com/cypress-io/cypress/issues/3090

**Comment by MSakamaki** [comment] 2021-07-24 14:23
This problem seems to be caused by the fact that Cypress internally uses Socket.io to communicate between node and browser.
In socket communication, the contents of the error object cannot be passed on, so an empty object is returned.
https://stackoverflow.com/questions/65123188/socket-io-emit-empty-object-if-its-an-error

As a workaround, you need to do some sort of serialization to bubble up the error.

I have implemented the following serializer and deserializer and confirmed that the error can be displayed without any problem.

```javascript
const errorSerialize = (error) => JSON.stringify(Object.getOwnPropertyNames(error).reduce( (obj, prop) => ({ ...obj, [prop]: error[prop] }), {} ));

class CompareSnapshotsPluginError extends Error {
  constructor(error) {
    super(error.message);
    Object.getOwnPropertyNames(error).filter(prop => prop !== 'message').forEach(prop => {
      this[prop] = error[prop];
    });
  }
}

const deserializeError = (error) => new CompareSnapshotsPluginError(JSON.parse(error));
```

use.

```javascript
// cypress-visual-regression/src/command.js
      cy.task('compareSnapshotsPlugin', options).then(results => {
        if (results.error) {
          throw deserializeError(results.error);
        }
```
```javascript
// cypress-visual-regression/src/plugin.js
  } catch (error) {
    return { error: errorSerialize(error) };
  }
```

Hopefully, I'll send a PR.

**Closed** 2021-07-28 22:47 UTC
