### ISSUE TITLE
Plugin crashes when comparing actual with non-existing base screenshot

### ISSUE THREAD

**Issue by greegus** [mjhea0/cypress-visual-regression#42] opened 2020-05-26 12:52 UTC
Plugin crashes and stops the whole spec when trying to compare an actual screenshot with a non-existing base. This could happen when you forgot to generate base images before, but in my opinion, it should be handled as a regular error and the test should carry on to another block within the test file.

```
The following error was thrown by a plugin. We stopped running your ****s because a plugin crashed. Please check your plugins file

Error: ENOENT: no such file or directory, open '/root/my-project/cypress/snapshots/base/homepage.spec.js/homepage-base.png'
```

**Comment by mjhea0** [comment] 2020-05-26 21:37
> but in my opinion, it should be handled as a regular error and the test should carry on to another block within the test file.

what's the use case?

**Comment by greegus** [comment] 2020-06-10 09:56
We are allocating some resources in our pipeline within the spec and those remain locked after the crash.

**Comment by minubharathyr** [comment] 2020-08-11 12:32
Plugin crashes even after upgrading to v1.4.0. If there is no base image because of some reason, then the whole run is getting aborted.

**Comment by mjhea0** [comment] 2020-08-11 12:46
@minubharathyr have you looked at https://github.com/mjhea0/cypress-visual-regression/pull/45 PR? Thoughts?

**Comment by minubharathyr** [comment] 2020-08-11 14:14
Yeah, according to the fix, the file should be parsed only if it exists. Don't know why it is still failing. 

**Error: ENOENT: no such file or directory.**

**Comment by mjhea0** [comment] 2020-08-11 14:51
I haven't merged the PR yet. I'm still waiting on @greegus to add some tests. Want to help with that @minubharathyr?

**Comment by greegus** [comment] 2020-08-11 15:14
@mjhea0 adding those specs right away.

**Comment by mjhea0** [comment] 2020-08-11 18:27
@minubharathyr version 1.5.0 is ready to go!

Thanks, @greegus!

https://www.npmjs.com/package/cypress-visual-regression

**Comment by mjhea0** [comment] 2020-08-11 18:37
Closing this. Please re-open if you are still having issues @minubharathyr.

**Closed by mjhea0** 2020-08-11 18:37 UTC
